// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.27.0
// source: proto/cv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhoAreYouParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WhoAreYouParams) Reset() {
	*x = WhoAreYouParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhoAreYouParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAreYouParams) ProtoMessage() {}

func (x *WhoAreYouParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAreYouParams.ProtoReflect.Descriptor instead.
func (*WhoAreYouParams) Descriptor() ([]byte, []int) {
	return file_proto_cv_proto_rawDescGZIP(), []int{0}
}

type Cv struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User   string   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Age    int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Skills []string `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
}

func (x *Cv) Reset() {
	*x = Cv{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_cv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cv) ProtoMessage() {}

func (x *Cv) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cv.ProtoReflect.Descriptor instead.
func (*Cv) Descriptor() ([]byte, []int) {
	return file_proto_cv_proto_rawDescGZIP(), []int{1}
}

func (x *Cv) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cv) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Cv) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Cv) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

var File_proto_cv_proto protoreflect.FileDescriptor

var file_proto_cv_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x11, 0x0a, 0x0f, 0x57, 0x68, 0x6f, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x73, 0x22, 0x52, 0x0a, 0x02, 0x43, 0x76, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x32, 0x31, 0x0a, 0x09, 0x43, 0x76, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6c, 0x6c, 0x12,
	0x10, 0x2e, 0x57, 0x68, 0x6f, 0x41, 0x72, 0x65, 0x59, 0x6f, 0x75, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x1a, 0x03, 0x2e, 0x43, 0x76, 0x22, 0x00, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_cv_proto_rawDescOnce sync.Once
	file_proto_cv_proto_rawDescData = file_proto_cv_proto_rawDesc
)

func file_proto_cv_proto_rawDescGZIP() []byte {
	file_proto_cv_proto_rawDescOnce.Do(func() {
		file_proto_cv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cv_proto_rawDescData)
	})
	return file_proto_cv_proto_rawDescData
}

var file_proto_cv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_cv_proto_goTypes = []interface{}{
	(*WhoAreYouParams)(nil), // 0: WhoAreYouParams
	(*Cv)(nil),              // 1: Cv
}
var file_proto_cv_proto_depIdxs = []int32{
	0, // 0: CvService.ListAll:input_type -> WhoAreYouParams
	1, // 1: CvService.ListAll:output_type -> Cv
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cv_proto_init() }
func file_proto_cv_proto_init() {
	if File_proto_cv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_cv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhoAreYouParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_cv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cv); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cv_proto_goTypes,
		DependencyIndexes: file_proto_cv_proto_depIdxs,
		MessageInfos:      file_proto_cv_proto_msgTypes,
	}.Build()
	File_proto_cv_proto = out.File
	file_proto_cv_proto_rawDesc = nil
	file_proto_cv_proto_goTypes = nil
	file_proto_cv_proto_depIdxs = nil
}
